---
title: "Maps"
author: "Trevor Isaacson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(maps)
library(viridis)
library(ggdendro)
library(plotly)
library(tigris)
library(mapview)
```

The data used for this assignment details mass shootings for the past five years.  Each entry includes the date, state, number of people who died, number of people that were injured and a small description describing what happened.  The data is available on Kaggle at https://www.kaggle.com/datasets/hemil26/mass-shootings-in-united-states-20182022?select=shootings_2018.csv.  

```{r}
states <- map_data("state")
states = states %>%
  mutate(State = str_to_title(region))

shootings2018 = read.csv("shootings_2018.csv")
shootings2019 = read.csv("shootings_2019.csv")
shootings2020 = read.csv("shootings_2020.csv")
shootings2021 = read.csv("shootings_2021.csv")
shootings2022 = read.csv("shootings_2022.csv")

shootingsTotal = bind_rows(shootings2018, shootings2019, shootings2020,
                           shootings2021, shootings2022)

shootingsTotal = shootingsTotal %>%
  group_by(State) %>%
  summarise(DeathTotal = sum(Dead))

shootings2018 = shootings2018 %>% 
  group_by(State) %>%
  summarise(DeathTotal = sum(Dead))
  
stateShootings2018 = states %>%
  left_join(shootings2018, by = "State") %>%
  select(-c(region, subregion))

head(stateShootings2018)
```

```{r}
p_death2018 = ggplot(data = stateShootings2018, 
       mapping = aes(x = long, y = lat, group = group, fill = DeathTotal,
                     text = paste("Shooting Deaths in 2018: ", DeathTotal))) +
  geom_polygon(color = "white") +
  ggdendro::theme_dendro() +
  scale_fill_viridis(option = "magma", direction = -1) + 
  coord_map() +
  guides(fill = guide_legend(title = "Deaths")) +
  ggtitle("Mass Shootings in 2018")

ggplotly(p_death2018, tooltip = "text")
```


```{r}
t_states <- tigris::states(cb = TRUE, resolution = '20m')

stateShootingsTotal = t_states %>%
  left_join(shootingsTotal, by =  c("NAME" = "State"))
```


```{r}
mapview::mapview(stateShootingsTotal, zcol = "DeathTotal")
```








